'use client'

import { useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, BatteryCharging, Bell, Boxes, BrainCircuit, Building2, CheckCircle2, ChevronDown, CircleGauge, CloudSnow, Command, Factory, FileText, Fuel, Gauge, HardHat, LayoutDashboard, Leaf, Menu, Package, Radio, Search, Settings, ShieldCheck, Snowflake, Sparkles, Thermometer, Truck, Wrench, X, Zap
} from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const nav = [
  ['Dashboard', LayoutDashboard], ['Stations', Building2], ['Digital Twin', Command], ['Energy', Zap], ['Infrastructure', Factory], ['Logistics', Boxes], ['Environment', CloudSnow], ['AI Insights', BrainCircuit], ['Alerts', Bell], ['Maintenance', Wrench], ['Simulation', Radio], ['Reports', FileText], ['Settings', Settings],
] as const

const power = [
  { time: '00', solar: 42, load: 108, battery: 82 }, { time: '04', solar: 18, load: 116, battery: 77 }, { time: '08', solar: 74, load: 128, battery: 74 }, { time: '12', solar: 132, load: 148, battery: 76 }, { time: '16', solar: 118, load: 154, battery: 72 }, { time: '20', solar: 58, load: 132, battery: 68 }, { time: '24', solar: 32, load: 120, battery: 65 },
]
const assets = [
  { name: 'Generator #02', type: 'Power System', station: 'Bharati', health: 61, temp: 94, status: 'Critical', risk: 'High', date: '12 Aug 2026' },
  { name: 'Generator #01', type: 'Power System', station: 'Maitri', health: 92, temp: 72, status: 'Normal', risk: 'Low', date: '21 Aug 2026' },
  { name: 'Heating Loop A', type: 'Heating', station: 'Bharati', health: 78, temp: 66, status: 'Warning', risk: 'Medium', date: '04 Jul 2026' },
  { name: 'Comms Tower', type: 'Communication', station: 'Maitri', health: 97, temp: 12, status: 'Normal', risk: 'Low', date: '01 Sep 2026' },
]

function StatusBadge({ status }: { status: string }) {
  const tone = status === 'Critical' ? 'critical' : status === 'Warning' || status === 'Attention Required' ? 'warning' : 'normal'
  return <span className={`badge ${tone}`}><span className="dot" />{status}</span>
}
function Metric({ icon: Icon, label, value, meta, tone = 'blue' }: any) {
  return <div className="metric-card"><div className={`metric-icon ${tone}`}><Icon size={18} /></div><div><p className="eyebrow">{label}</p><div className="metric-value">{value}</div>{meta && <p className="muted">{meta}</p>}</div></div>
}
function Section({ title, eyebrow, children, action }: any) { return <section className="section"><div className="section-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action}</div>{children}</section> }

export default function Page() {
  const [page, setPage] = useState('Dashboard')
  const [station, setStation] = useState('All Stations')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [sim, setSim] = useState<'normal' | 'failure' | 'fuel' | 'weather'>('normal')
  const [selectedAsset, setSelectedAsset] = useState<any>(null)
  const [ack, setAck] = useState(false)
  const failure = sim === 'failure'
  const fuel = sim === 'fuel'
  const liveAssets = useMemo(() => assets.map((asset) => asset.name === 'Generator #02' && failure ? { ...asset, health: 42, temp: 96, status: 'Critical' } : asset), [failure])
  const temp = failure ? 96 : 72
  const fuelLevel = fuel ? 18 : 68

  const go = (name: string) => { setPage(name); setMobileOpen(false) }
  const runSim = (mode: any) => { setSim(mode); if (mode === 'failure') setPage('Digital Twin') }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Snowflake size={19} /></div><div><strong>POLAR<span>-TWIN</span></strong><small>REMOTE OPERATIONS</small></div><button className="icon-btn mobile-close" onClick={() => setMobileOpen(false)}><X size={18} /></button></div>
      <div className="demo-pill"><span className="pulse" /> SIMULATION / DEMO DATA</div>
      <nav>{nav.map(([label, Icon]) => <button key={label} className={page === label ? 'nav-item active' : 'nav-item'} onClick={() => go(label)}><Icon size={17} /><span>{label}</span>{label === 'Alerts' && <b>3</b>}</button>)}</nav>
      <div className="sidebar-footer"><div className="avatar">RM</div><div><strong>Riya Menon</strong><small>Research Operations Manager</small></div><ChevronDown size={15} /></div>
    </aside>
    <main className="main"><header className="topbar"><button className="icon-btn menu-btn" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="station-select"><span className="live-dot" /> <span>{station}</span><ChevronDown size={14} /></div><div className="top-actions"><div className="search"><Search size={16} /><input aria-label="Search" placeholder="Search assets, alerts..." /></div><button className="icon-btn"><Bell size={18} /><i /></button><span className="system-status"><span className="live-dot" /> All systems nominal</span></div></header>
      <div className="content">
        <div className="page-heading"><div><p className="eyebrow">ANTARCTIC OPERATIONS CENTER <span className="heading-line" /></p><h1>{page === 'Dashboard' ? 'Command Center' : page}</h1><p className="subheading">{page === 'Dashboard' ? 'Unified digital twin monitoring and decision support for Indian Antarctic stations.' : `Monitor and manage ${page.toLowerCase()} across Maitri and Bharati stations.`}</p></div><div className="station-tabs">{['Maitri', 'Bharati', 'All Stations'].map(s => <button key={s} className={station === s ? 'selected' : ''} onClick={() => setStation(s)}>{s}</button>)}</div></div>
        {page === 'Dashboard' && <Dashboard failure={failure} fuel={fuel} temp={temp} fuelLevel={fuelLevel} onNavigate={go} />}
        {page === 'Digital Twin' && <Twin temp={temp} failure={failure} selectedAsset={selectedAsset} setSelectedAsset={setSelectedAsset} />}
        {page === 'Simulation' && <Simulation sim={sim} runSim={runSim} />}
        {page === 'Energy' && <Energy />}
        {page === 'Infrastructure' && <Infrastructure assets={liveAssets} />}
        {page === 'Logistics' && <Logistics fuel={fuel} fuelLevel={fuelLevel} />}
        {page === 'Environment' && <Environment weather={sim === 'weather'} />}
        {page === 'AI Insights' && <Insights failure={failure} fuel={fuel} />}
        {page === 'Alerts' && <Alerts failure={failure} fuel={fuel} ack={ack} setAck={setAck} />}
        {page === 'Maintenance' && <Maintenance />}
        {['Stations', 'Reports', 'Settings'].includes(page) && <Placeholder page={page} />}
      </div>
    </main>
  </div>
}

function Dashboard({ failure, fuel, temp, fuelLevel, onNavigate }: any) { return <>
  <div className="station-grid"><StationCard name="MAITRI" status="Operational" temp="-24°C" energy="76%" fuel="81%" health="92%" /><StationCard name="BHARATI" status={failure ? 'Attention Required' : 'Operational'} temp="-29°C" energy="64%" fuel={`${fuelLevel}%`} health={failure ? '78%' : '86%'} /></div>
  <div className="metrics-grid"><Metric icon={ShieldCheck} label="Station Health" value={failure ? '82%' : '86%'} meta="-4.2% vs last hour" tone="cyan" /><Metric icon={Zap} label="Energy Efficiency" value="87%" meta="+3.6% vs yesterday" tone="yellow" /><Metric icon={Bell} label="Active Alerts" value={failure || fuel ? '4' : '3'} meta="2 requiring action" tone="red" /><Metric icon={Wrench} label="Critical Assets" value={failure ? '3' : '2'} meta="Across all stations" tone="purple" /><Metric icon={Package} label="Inventory Risk" value={fuel ? '5' : '4'} meta="Items below threshold" tone="orange" /><Metric icon={HardHat} label="Maintenance Due" value="3" meta="Next 14 days" tone="blue" /></div>
  <div className="grid-2"><Section title="Live sensor telemetry" eyebrow="REAL-TIME MONITORING" action={<span className="live-label"><span className="pulse" /> LIVE</span>}><div className="sensor-grid"><Sensor icon={Thermometer} label="Outside temperature" value="-28°C" /><Sensor icon={Activity} label="Wind speed" value="42 km/h" /><Sensor icon={Gauge} label="Pressure" value="982 hPa" /><Sensor icon={CloudSnow} label="Visibility" value="8.4 km" /><Sensor icon={Zap} label="Solar generation" value="125 kW" /><Sensor icon={CircleGauge} label="Power consumption" value="150 kW" /><Sensor icon={BatteryCharging} label="Battery level" value="76%" /><Sensor icon={Fuel} label="Fuel level" value={`${fuelLevel}%`} warning={fuel} /></div></Section><Section title="AI operations intelligence" eyebrow="SYNTHETIC ANALYTICS" action={<button className="text-btn" onClick={() => onNavigate('AI Insights')}>View all <span>→</span></button>}><div className="insight-card critical-bg"><div className="insight-icon"><AlertTriangle size={18} /></div><div><div className="insight-title">{failure ? 'Generator #02 overheating' : 'Generator anomaly detected'}</div><p>{failure ? 'Abnormal temperature trend detected at Bharati.' : 'Early warning: Generator #02 temperature trending upward.'}</p><div className="insight-meta"><span className="badge critical">HIGH RISK</span><span>92% confidence</span></div></div></div><div className="insight-card"><div className="insight-icon cyan"><Sparkles size={18} /></div><div><div className="insight-title">Energy forecast</div><p>Expected consumption tomorrow: <strong>+12%</strong>. Shift non-critical loads to peak solar hours.</p><div className="insight-meta"><span className="badge normal">RECOMMENDATION</span></div></div></div></Section></div>
  <Section title="Station health overview" eyebrow="DIGITAL TWIN STATUS" action={<button className="outline-btn" onClick={() => onNavigate('Digital Twin')}>Open digital twin <Command size={14} /></button>}><div className="chart-card"><ResponsiveContainer width="100%" height={210}><AreaChart data={power}><defs><linearGradient id="health" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity={.3}/><stop offset="100%" stopColor="#22d3ee" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1c344b" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time" stroke="#6b8299" tickLine={false} axisLine={false}/><YAxis stroke="#6b8299" tickLine={false} axisLine={false} domain={[0,180]}/><Tooltip contentStyle={{background:'#0d2033',border:'1px solid #24445e',borderRadius:8}}/><Area type="monotone" dataKey="load" stroke="#22d3ee" fill="url(#health)" strokeWidth={2}/><Line type="monotone" dataKey="solar" stroke="#e8b94a" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer><div className="chart-legend"><span><i className="cyan-line" /> Power consumption</span><span><i className="yellow-line" /> Solar generation</span><span className="muted">Last 24 hours · Simulated data</span></div></div></Section>
</> }
function StationCard({ name, status, temp, energy, fuel, health }: any) { return <div className="station-card"><div className="station-card-top"><div><p className="eyebrow">STATION</p><h3>{name}</h3></div><StatusBadge status={status} /></div><div className="station-temp"><Thermometer size={18} /><strong>{temp}</strong><span>Outside temperature</span></div><div className="station-bars"><BarStat label="Energy" value={energy} color="cyan" /><BarStat label="Fuel" value={fuel} color="yellow" /><BarStat label="Infrastructure" value={health} color="purple" /></div></div> }
function BarStat({ label, value, color }: any) { return <div className="bar-stat"><div><span>{label}</span><strong>{value}</strong></div><div className="bar"><i className={color} style={{width:value}} /></div></div> }
function Sensor({ icon: Icon, label, value, warning }: any) { return <div className="sensor"><Icon size={16} className={warning ? 'warning-icon' : ''} /><div><span>{label}</span><strong>{value}</strong></div><span className={`sensor-state ${warning ? 'warning-text' : ''}`} /> </div> }

function Twin({ temp, failure, selectedAsset, setSelectedAsset }: any) { const nodes = [{n:'Main Building', x:37,y:43,s:'normal'}, {n:'Research Lab',x:63,y:40,s:'normal'}, {n:'Generator #02',x:24,y:68,s:failure?'critical':'normal'}, {n:'Battery Storage',x:48,y:73,s:'normal'}, {n:'Fuel Storage',x:75,y:70,s:'normal'}, {n:'Warehouse',x:83,y:43,s:'normal'}, {n:'Medical Unit',x:13,y:42,s:'normal'}, {n:'Comms Tower',x:91,y:19,s:'normal'}]; return <div className="twin-layout"><Section title="Antarctic station · Bharati" eyebrow="INTERACTIVE DIGITAL TWIN" action={<div className="legend"><span><i className="green"/> Normal</span><span><i className="amber"/> Warning</span><span><i className="red"/> Critical</span></div>}><div className="twin-canvas"><div className="snow-grid" /><div className="tower-line" /><div className="road" />{nodes.map((node) => <button key={node.n} className={`twin-node ${node.s}`} style={{left:`${node.x}%`,top:`${node.y}%`}} onClick={() => setSelectedAsset(node)}><span className="node-dot" /><span>{node.n}</span></button>)}<div className="canvas-label">BHARATI RESEARCH STATION · SYNTHETIC DIGITAL TWIN</div></div></Section><div className="twin-side"><div className="panel-header"><div><p className="eyebrow">ASSET INSPECTOR</p><h3>{selectedAsset?.n || 'Select an asset'}</h3></div><StatusBadge status={selectedAsset?.s === 'critical' ? 'Critical' : selectedAsset ? 'Normal' : 'Awaiting selection'} /></div>{selectedAsset ? <><div className="asset-big"><Thermometer size={21}/><div><span>Temperature</span><strong>{selectedAsset.n === 'Generator #02' ? `${temp}°C` : '—'}</strong></div><div><span>Health score</span><strong>{selectedAsset.n === 'Generator #02' && failure ? '42%' : '94%'}</strong></div></div><div className="detail-list"><div><span>Load</span><strong>{failure && selectedAsset.n === 'Generator #02' ? '96%' : '72%'}</strong></div><div><span>Vibration</span><strong className={failure ? 'warning-text' : ''}>{failure ? 'HIGH' : 'LOW'}</strong></div><div><span>Runtime</span><strong>1,842 hrs</strong></div></div><div className="ai-callout"><BrainCircuit size={18}/><div><strong>AI Analysis</strong><p>{failure ? 'Abnormal temperature trend detected.' : 'Asset operating within expected parameters.'}</p></div></div><button className="primary-btn"><Wrench size={15}/> Create maintenance request</button><button className="outline-btn full">Acknowledge alert</button></> : <div className="empty-panel"><Command size={30}/><p>Click an asset on the station layout to inspect telemetry, health and AI recommendations.</p></div>}</div></div> }

function Simulation({ sim, runSim }: any) { return <div className="sim-page"><div className="sim-hero"><div><div className="sim-kicker"><Radio size={14}/> SYNTHETIC SENSOR ENGINE</div><h2>Antarctic Station Simulator</h2><p>Inject controlled scenarios into the digital twin to demonstrate detection, prediction and remote decision support.</p></div><div className="sim-status"><span className="pulse" /> SIMULATION ACTIVE</div></div><div className="scenario-grid">{[['normal','Normal operation','All systems nominal',CheckCircle2,'green'],['failure','Simulate generator failure','Temperature escalation',AlertTriangle,'red'],['fuel','Simulate low fuel','Resupply risk forecast',Fuel,'amber'],['weather','Simulate extreme weather','High wind + low visibility',CloudSnow,'blue']].map(([id,title,desc,Icon,color]: any) => <button className={`scenario ${sim === id ? 'active' : ''}`} key={id} onClick={() => runSim(id)}><div className={`scenario-icon ${color}`}><Icon size={20}/></div><strong>{title}</strong><span>{desc}</span><em>{sim === id ? 'ACTIVE' : 'RUN SCENARIO'} →</em></button>)}</div><div className="sim-flow"><div className="flow-head"><div><p className="eyebrow">LIVE SCENARIO OUTPUT</p><h3>{sim === 'failure' ? 'Generator #02 failure cascade' : sim === 'fuel' ? 'Fuel depletion forecast' : sim === 'weather' ? 'Extreme weather event' : 'Normal operations baseline'}</h3></div><StatusBadge status={sim === 'normal' ? 'Normal' : 'Critical'} /></div><div className="flow-steps">{(sim === 'failure' ? [['T+00','72°C','Normal'],['T+10','78°C','Monitoring'],['T+20','85°C','Warning'],['T+30','91°C','Critical'],['T+40','96°C','Critical']] : sim === 'fuel' ? [['Now','68%','Normal'],['Day 2','45%','Monitoring'],['Day 5','30%','Warning'],['Day 9','18%','Critical']] : [['Now','Nominal','Normal'],['+6h','Nominal','Normal'],['+12h','Nominal','Normal']]).map(([time,value,status]: any) => <div className="flow-step" key={time}><span>{time}</span><strong>{value}</strong><StatusBadge status={status}/></div>)}</div>{sim !== 'normal' && <div className="sim-result"><AlertTriangle size={18}/><div><strong>{sim === 'fuel' ? 'Critical fuel alert generated' : 'Anomaly detected automatically'}</strong><p>{sim === 'fuel' ? 'Resupply mission recommended. Medical and fuel logistics teams notified.' : 'AI insight created: inspect cooling system and reduce non-critical load.'}</p></div></div>}</div></div> }

function Energy() { return <><div className="kpi-strip"><Metric icon={Zap} label="Solar generation" value="125 kW" meta="Peak at 12:00" tone="yellow"/><Metric icon={Activity} label="Power consumption" value="150 kW" meta="+8.2% today" tone="cyan"/><Metric icon={BatteryCharging} label="Battery state" value="76%" meta="Charging" tone="purple"/><Metric icon={Fuel} label="Fuel consumption" value="1,240 L" meta="This week" tone="orange"/></div><div className="grid-2"><Section title="24-hour power profile" eyebrow="ENERGY TELEMETRY"><div className="chart-card tall"><ResponsiveContainer width="100%" height={280}><LineChart data={power}><CartesianGrid stroke="#1c344b" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time" stroke="#6b8299"/><YAxis stroke="#6b8299"/><Tooltip contentStyle={{background:'#0d2033',border:'1px solid #24445e'}}/><Line dataKey="load" stroke="#22d3ee" strokeWidth={3}/><Line dataKey="solar" stroke="#e8b94a" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Section><Section title="AI energy forecast" eyebrow="PREDICTIVE ANALYTICS"><div className="forecast"><Sparkles size={22}/><div><h3>Expected consumption tomorrow: <span>+12%</span></h3><p>Shift non-critical loads toward peak solar-generation hours between 10:00 and 15:00 to preserve fuel reserves.</p><button className="outline-btn">Apply recommendation</button></div></div><div className="energy-flow"><span>Solar <Zap size={14}/></span><b>→</b><span>Battery <BatteryCharging size={14}/></span><b>→</b><span>Station <Building2 size={14}/></span></div></Section></div></> }
function Infrastructure({ assets }: any) { return <Section title="Asset health registry" eyebrow="INFRASTRUCTURE MONITORING" action={<button className="outline-btn"><Wrench size={14}/> Create work order</button>}><div className="filter-row"><button className="filter active">All assets</button><button className="filter">Critical</button><button className="filter">Warnings</button><button className="filter">Bharati</button></div><div className="table-wrap"><table><thead><tr><th>Asset</th><th>Station</th><th>Status</th><th>Health</th><th>Temperature</th><th>Last maintenance</th><th>Risk</th></tr></thead><tbody>{assets.map((a: any) => <tr key={a.name}><td><strong>{a.name}</strong><small>{a.type}</small></td><td>{a.station}</td><td><StatusBadge status={a.status}/></td><td><div className="health-cell"><span>{a.health}%</span><div className="bar"><i className={a.health < 70 ? 'red' : 'cyan'} style={{width:`${a.health}%`}}/></div></div></td><td>{a.temp}°C</td><td>{a.date}</td><td><span className={a.risk === 'High' ? 'warning-text' : ''}>{a.risk}</span></td></tr>)}</tbody></table></div></Section> }
function Logistics({ fuel, fuelLevel }: any) { return <><div className="inventory-grid">{[['Fuel',fuel ? `${fuelLevel}%`:'8,100 L',fuel?'Critical':'Normal',Fuel],['Medicine','42 units','Warning',Activity],['Spare parts','18 units','Warning',Wrench],['Emergency supplies','96 units','Normal',ShieldCheck]].map(([name,value,status,Icon]: any) => <div className="inventory-card" key={name}><div className="inventory-icon"><Icon size={18}/></div><span>{name}</span><strong>{value}</strong><StatusBadge status={status}/><div className="bar"><i className={status === 'Critical' ? 'red' : status === 'Warning' ? 'amber':'cyan'} style={{width:status==='Normal'?'81%':'42%'}}/></div></div>)}</div><Section title="Inventory risk forecast" eyebrow="LOGISTICS & RESUPPLY"><div className="risk-row"><div className="risk-symbol"><AlertTriangle size={20}/></div><div><strong>{fuel ? 'Fuel shortage risk at Bharati' : 'Medical supplies below minimum threshold'}</strong><p>AI prediction: current consumption trend may cause shortage within approximately <b>{fuel ? '6' : '9'} days.</b></p></div><button className="primary-btn">Create resupply request</button></div></Section></> }
function Environment({ weather }: any) { return <><div className="metrics-grid"><Metric icon={Thermometer} label="Temperature" value="-29°C" meta="Falling 2.4°C / hr" tone="cyan"/><Metric icon={Activity} label="Wind speed" value={weather?'68 km/h':'48 km/h'} meta={weather?'Severe conditions':'Moderate'} tone="yellow"/><Metric icon={CloudSnow} label="Visibility" value={weather?'1.2 km':'8.4 km'} meta={weather?'Low':'Clear'} tone="purple"/><Metric icon={Leaf} label="Environmental risk" value={weather?'HIGH':'LOW'} meta="AI risk assessment" tone={weather?'red':'green'}/></div><div className="grid-2"><Section title="Environmental conditions" eyebrow="LIVE WEATHER TELEMETRY"><div className="chart-card"><ResponsiveContainer width="100%" height={260}><LineChart data={power}><CartesianGrid stroke="#1c344b" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time" stroke="#6b8299"/><YAxis stroke="#6b8299"/><Tooltip contentStyle={{background:'#0d2033',border:'1px solid #24445e'}}/><Line dataKey="load" name="Wind trend" stroke="#a78bfa" strokeWidth={3}/><Line dataKey="solar" name="Temperature trend" stroke="#22d3ee" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Section><Section title="Environmental risk" eyebrow="AI RISK DETECTION"><div className={`environment-alert ${weather?'high':''}`}><CloudSnow size={25}/><div><span>Current assessment</span><strong>{weather?'HIGH':'LOW'} RISK</strong><p>{weather?'Restrict non-essential outdoor operations during severe weather conditions.':'Conditions are suitable for planned outdoor research operations.'}</p></div></div></Section></div></> }
function Insights({ failure, fuel }: any) { const items = [{title:'Generator anomaly',asset:'Generator #02 · Bharati',desc:failure?'Abnormal temperature increase detected.':'Early temperature trend deviation detected.',conf:'92%',risk:'High',icon:AlertTriangle},{title:'Energy forecast',asset:'Station-wide · Tomorrow',desc:'Energy consumption expected to increase by 12%.',conf:'88%',risk:'Medium',icon:Zap},{title:'Inventory forecast',asset:'Medical inventory · Maitri',desc:`Medical inventory may reach critical threshold in approximately ${fuel?'6':'9'} days.`,conf:'84%',risk:'Medium',icon:Package},{title:'Environmental risk',asset:'Bharati · Weather system',desc:'High wind and low visibility detected.',conf:'91%',risk:'High',icon:CloudSnow}]; return <div className="insight-grid">{items.map(({title,asset,desc,conf,risk,icon:Icon}) => <div className="full-insight" key={title}><div className="full-insight-top"><div className="insight-icon cyan"><Icon size={19}/></div><StatusBadge status={risk === 'High'?'Critical':'Warning'}/></div><p className="eyebrow">{asset}</p><h3>{title}</h3><p>{desc}</p><div className="confidence"><span>Confidence</span><strong>{conf}</strong><div className="bar"><i className="cyan" style={{width:conf}}/></div></div><button className="outline-btn full">View recommendation →</button></div>)}</div> }
function Alerts({ failure, fuel, ack, setAck }: any) { const list = [{severity:'Critical',title:failure?'Generator #02 overheating':'Generator #02 temperature above safe threshold',station:'Bharati',time:'2 min ago',desc:'Abnormal temperature trend detected. Inspect cooling system and reduce non-critical load.'},{severity:'Warning',title:fuel?'Fuel reserve below critical threshold':'Medical inventory below minimum threshold',station:'Maitri',time:'18 min ago',desc:'Consumption trend indicates a potential shortage in the next 9 days.'},{severity:'Warning',title:'High wind speed detected',station:'Bharati',time:'42 min ago',desc:'Restrict non-essential outdoor operations.'}]; return <Section title="Alert management" eyebrow="EVENT STREAM" action={<span className="muted">{list.length} active events</span>}><div className="alert-list">{list.map((a) => <div className={`alert-row ${a.severity.toLowerCase()}`} key={a.title}><div className="alert-severity"><AlertTriangle size={17}/></div><div className="alert-main"><div><StatusBadge status={a.severity}/><span className="muted">{a.time} · {a.station}</span></div><strong>{a.title}</strong><p>{a.desc}</p></div><button className="outline-btn" onClick={() => setAck(true)}>{ack?'Acknowledged':'Acknowledge'}</button></div>)}</div></Section> }
function Maintenance() { return <Section title="Predictive maintenance" eyebrow="ASSET RELIABILITY" action={<button className="primary-btn"><Wrench size={14}/> Create work order</button>}><div className="kpi-strip"><Metric icon={Wrench} label="Maintenance due" value="3" meta="Next 14 days" tone="yellow"/><Metric icon={AlertTriangle} label="Overdue" value="1" meta="Requires attention" tone="red"/><Metric icon={BrainCircuit} label="Predicted" value="5" meta="AI identified" tone="purple"/><Metric icon={CheckCircle2} label="Completed" value="12" meta="This month" tone="green"/></div><div className="table-wrap"><table><thead><tr><th>Asset</th><th>Station</th><th>Health</th><th>Risk</th><th>Last maintenance</th><th>Predicted maintenance</th><th>Action</th></tr></thead><tbody>{assets.slice(0,3).map(a=><tr key={a.name}><td><strong>{a.name}</strong></td><td>{a.station}</td><td>{a.health}%</td><td><span className={a.risk==='High'?'warning-text':''}>{a.risk}</span></td><td>{a.date}</td><td>Within 7 days</td><td><button className="text-btn">Create work order →</button></td></tr>)}</tbody></table></div></Section> }
function Placeholder({page}:any){return <div className="placeholder"><div className="brand-mark"><Snowflake size={22}/></div><h2>{page} workspace</h2><p>This operational workspace is ready for station data, reports and team configuration.</p><button className="primary-btn">Open workspace</button></div>}
